/*
 * This source file was generated by the Gradle 'init' task
 */
package org.daichiOS;

import org.daichiOS.repository.BookRepository;
import org.daichiOS.repository.UserRepository;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;

@SpringBootTest(properties = "spring.data.mongodb.auto-index-creation=false")
class AppTest {
  @MockBean private MongoTemplate mongoTemplate;
  @MockBean private BookRepository bookRepository;
  @MockBean private UserRepository userRepository;
  @MockBean private PasswordEncoder passwordEncoder;

  // @Test
  // void contextLoads() {
  // // This test verifies that the Spring context loads successfully
  // }
}
